### ISSUE TITLE
Первые шаги

### ISSUE THREAD

**Issue by wldmr-key** [daria40tim/Transform_Cards#1]
С темой все нормально
Я правильно понимаю, что ты ее хочешь сделать и темой для ВКР?
Прежде всего придумай нормальное название. Вряд ли назначением работы является автоматизация ООО...
Прикинь, задача оцифровки сама по себе является достаточно нетривиальной. Не стоит ли тебе ее выделить в тему крсовой по мимапр?
И, подумай недельку над темой НИР, которая была бы тебе интересна

**Comment by daria40tim** [comment]
Да, это и будет темой для ВКР. Разработка системы хранения и обработки технических данных о трансформаторах на производственном предприятии? 
Добавила в репозиторий концептуальную схему данных. Ссылка: https://github.com/daria40tim/Transform_Cards/blob/master/Концептуальная%20схема.png
Трехфазный трансформатор - это не отдельно стоящая сущность, на него действуют все те же соединения, что и для двухфазного.
Также добавила прототип интерфейса системы. 
По поводу НИРа: я могу сделать сравнительный анализ фреймворков для распознавания печатного текста с изображения, а потом сослаться на эту работу в ВКР в системе оцифровки. Распознанные сканы получить нет возможности. 
А еще у меня есть голубая мечта сделать читалку на мобильные платформы со встроенным переводчиком. Для этого понадобится система анализа текста и поиска наименее часто встречающихся слов (как правило, они и есть самые сложные). Могу написать об этом.

**Comment by wldmr-key** [comment]
Тему первых шагов можно считать исчерпанной ))
Я открыл новые задачи по следующим шагам
