### ISSUE TITLE
Разработать техническое задание

### ISSUE THREAD

**Issue by wldmr-key** [daria40tim/Transform_Cards#2]
К тексту нареканий практически нет
Заменить тему "Исследование и разработка программной системы для оптимизации работы ООО «Электротехнический завод" (оптимизации!!!)
Добавить титульник
Поверить соответствие ГОСТ, в том числе, по оформлению 
Заполнить бланк Задания на выполнение курсовой работы

**Comment by daria40tim** [comment]
Прикладываю титульник и бланк отдельным файлом. 
[титульники.docx](https://github.com/daria40tim/Transform_Cards/files/3621763/default.docx)
